### ISSUE TITLE
Cannot use ICE client using v0.1.0-rc1

### ISSUE THREAD

**Issue by lacan** [qupath/qupath-extension-omero#1]
When connecting to our OMERO instance using https://omero.epfl.ch, we are able to browse all the files. 

We also included the files necessary to have the ICE API being recognized
![image](https://github.com/qupath/qupath-extension-omero/assets/319932/68d7c819-7708-4a4f-915d-3fc7a776ab40)

Unfortunately upon trying to import a Fluorescent image we receive

```
Unable to create OMERO server
omero.ClientError: Obtained null object proxy
	at omero.client.createSession(client.java:796)
	at omero.gateway.Gateway.createSession(Gateway.java:1034)
	at omero.gateway.Gateway.connect(Gateway.java:295)
	at qupath.ext.omero.core.pixelapis.ice.IceReader.connect(IceReader.java:159)
	at qupath.ext.omero.core.pixelapis.ice.IceReader.<init>(IceReader.java:58)
	at qupath.ext.omero.core.pixelapis.ice.IceAPI.createReader(IceAPI.java:85)
	at qupath.ext.omero.core.imageserver.OmeroImageServer.create(OmeroImageServer.java:72)
	at qupath.ext.omero.core.imageserver.OmeroImageServerBuilder.lambda$buildServer$0(OmeroImageServerBuilder.java:30)
	at java.base/java.util.Optional.flatMap(Unknown Source)
	at qupath.ext.omero.core.imageserver.OmeroImageServerBuilder.buildServer(OmeroImageServerBuilder.java:30)
	at qupath.ext.omero.core.imageserver.OmeroImageServerBuilder.lambda$checkImageSupport$1(OmeroImageServerBuilder.java:44)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
	at qupath.ext.omero.core.imageserver.OmeroImageServerBuilder.checkImageSupport(OmeroImageServerBuilder.java:52)
	at qupath.lib.images.servers.ImageServers.getImageSupport(ImageServers.java:387)
	at qupath.lib.images.servers.ImageServers.getImageSupport(ImageServers.java:419)
	at qupath.lib.gui.commands.ProjectImportImagesCommand$1.lambda$call$0(ProjectImportImagesCommand.java:366)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

This is caused by the fact that our IT service separated omero.server (ICE) from omero.web (Web API) by giving them separate aliases and certificates, which is apparently best practice, but means that we cannot use ICE with the extension as-is because the OMERO Extension would need to authenticate to 
https://omero-server.epfl.ch
instead of 
https://omero.epfl.ch

Because there is no Web API accessible via https://omero-server.epfl.ch, we cannot enter the Extension using that URL, because then we get the error

```
Could not find API URL in https://omero-server.epfl.ch/api/
Connection to https://omero-server.epfl.ch/api/ failed
java.util.concurrent.CompletionException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
	at java.net.http/jdk.internal.net.http.Http1Exchange.lambda$cancelImpl$9(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at java.net.http/jdk.internal.net.http.ResponseTimerEvent.handle(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl.purgeTimeoutsAndReturnNextDeadline(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(Unknown Source)
Caused by: java.net.ConnectException: HTTP connect timed out
	... 3 more
```

So this would mean for us that in the Settings, there should be a **Ice API server address** that could be set to something else than the Web API one. 
![image](https://github.com/qupath/qupath-extension-omero/assets/319932/28ffa401-6897-4043-8c6e-ead5cf8dc161)

We will test the **OMERO Pixel Data Microservice** after our IT install it on our OMERO test server and get back to you.

**Comment by psobolewskiPhD** [comment]
I've got this same issue I think here at JAX where our web and omero servers are separated.
I can't even see the files, everything is <hidden> probably due to permissions.

**Comment by psobolewskiPhD** [comment]
This isn't quite working yet.
It looks like the hostname entered into the Settings isn't being used correctly, just the first part is.
You can see it using `ctomero` and not `ctomero.jax.org`.
```
15:45:48.645	[JavaFX Application Thread]	INFO	qupath.ext.omero.core.pixelapis.ice.IceReader	Can't connect to ctomero:4064	omero.gateway.exception.DSOutOfServiceException: Can't resolve hostname ctomero
	at omero.gateway.Gateway.connect(Gateway.java:312)
	at qupath.ext.omero.core.pixelapis.ice.IceReader.connect(IceReader.java:150)
	at qupath.ext.omero.core.pixelapis.ice.IceReader.<init>(IceReader.java:57)
	at qupath.ext.omero.core.pixelapis.ice.IceAPI.createReader(IceAPI.java:156)
	at qupath.ext.omero.core.imageserver.OmeroImageServer.create(OmeroImageServer.java:72)
	at qupath.ext.omero.core.imageserver.OmeroImageServerBuilder.lambda$buildServer$0(OmeroImageServerBuilder.java:30)
	at java.base/java.util.Optional.flatMap(Unknown Source)
	at qupath.ext.omero.core.imageserver.OmeroImageServerBuilder.buildServer(OmeroImageServerBuilder.java:30)
	at qupath.lib.images.servers.ImageServerBuilder$DefaultImageServerBuilder.buildOriginal(ImageServerBuilder.java:350)
	at qupath.lib.images.servers.ImageServerBuilder$AbstractServerBuilder.build(ImageServerBuilder.java:174)
	at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:1713)
	at qupath.ext.omero.gui.UiUtilities.openImages(UiUtilities.java:152)
	at qupath.ext.omero.gui.browser.serverbrowser.Browser.onImagesTreeClicked(Browser.java:226)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:72)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:270)
	at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:84)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1853)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1726)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3684)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3989)
	at javafx.scene.Scene.processMouseEvent(Scene.java:1890)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2704)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
Caused by: Ice.DNSException
    error = 0
    host = "ctomero"
	at IceInternal.AsyncResultI.__wait(AsyncResultI.java:276)
	at Ice.ObjectPrxHelperBase.end_ice_isA(ObjectPrxHelperBase.java:310)
	at Ice.ObjectPrxHelperBase.ice_isA(ObjectPrxHelperBase.java:92)
	at Ice.ObjectPrxHelperBase.ice_isA(ObjectPrxHelperBase.java:69)
	at Ice.ObjectPrxHelperBase.checkedCastImpl(ObjectPrxHelperBase.java:2810)
	at Ice.ObjectPrxHelperBase.checkedCastImpl(ObjectPrxHelperBase.java:2770)
	at Glacier2.RouterPrxHelper.checkedCast(RouterPrxHelper.java:1787)
	at omero.client.getRouter(client.java:848)
	at omero.client.createSession(client.java:769)
	at omero.gateway.Gateway.createSession(Gateway.java:1034)
	at omero.gateway.Gateway.connect(Gateway.java:295)
	... 49 more
Caused by: java.net.UnknownHostException: ctomero
	at java.base/java.net.InetAddress$CachedLookup.get(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
	at IceInternal.Network.getAddresses(Network.java:832)
	at IceInternal.EndpointHostResolver$1.run(EndpointHostResolver.java:103)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by Rylern** [comment]
When opening an image with the ICE API, two (or three) URLs will be tested:
* The omero.web address.
* The omero.server address indicated on <omero.web address>/api/v0/servers/
* The address indicated by the user in the `Settings` window (if the user indicated one).

If connecting to one address doesn't work, the next one is tested.

I think the log you mentionned refers to the connection attempt on the omero.server address indicated on <omero.web address>/api/v0/servers/. It didn't work, but the address indicated by you in the `Settings` window did, so the image opened. You won't see OMERO (Ice) in the Image tab if the connection failed or if another API is used.

The log message was not very clear about this behavior. I improved it in the [v0.1.0-rc3 release](https://github.com/qupath/qupath-extension-omero/releases/tag/v0.1.0-rc3).

**Comment by psobolewskiPhD** [comment]
I no longer see any logs from the extension when logging in or doing things.
I'm still not sure I understand how everything works -- how are my credentials handled? When I log in via the extension to the web server, we only see a web login on our servers, no login on the actual omero server. I don't get a prompt for the omero server -- are you caching my credentials?
Also when opening an image via Ice (in theory) the URI points to a location on the web server.

**Comment by Rylern** [comment]
> I no longer see any logs from the extension when logging in or doing things.

I only used logs to display warnings or errors, so it means everything works fine.

> I'm still not sure I understand how everything works -- how are my credentials handled? When I log in via the extension to the web server, we only see a web login on our servers, no login on the actual omero server. I don't get a prompt for the omero server -- are you caching my credentials?

When you log in via the extension to the browser, a connection is made to the omero.web instance.

When you open an image with the ICE API, a new connection is made to the omero.server instance. The connection is made using a session UUID got from the web API (see the response of [this request](https://omero.readthedocs.io/en/stable/developers/json-api.html#login)) which can be used instead of a username/password. So only this session UUID is cached, not the password.

>  Also when opening an image via Ice (in theory) the URI points to a location on the web server.

The pixel APIs (Web API, Ice API, pixel data microservice API) are only about retrieving **pixel values**. Everything else (for example image metadata) is retrieved using the omero.web instance. It's implemented this way to minimize the code specific to each pixel API, and because only pixel values will differ between the different APIs (the image width will be the same if retrieved through the omero.server instance or the omero.web instance for example).

This is why the URI points to a location on the web server. In practise, if the ICE API is selected, the URI by itself won't be used, but the image ID (contained in the URI) will.

**Comment by psobolewskiPhD** [comment]
Thanks for the detailed response, everything makes sense now.
I'd suggest adding that to the README/documentation.

I do think that basic informative logging for the connection process would be useful?

On my end everything seems to be working, but I will let @lacan chime in.

**Comment by Rylern** [comment]
OK thanks, I updated the README and I added INFO logs when connecting / disconnecting. They will be shown on the next release.

**Comment by Rylern** [comment]
Hi @lacan, are you able to use ICE with the [last version of the extension](https://github.com/qupath/qupath-extension-omero/releases/tag/v0.1.0-rc4)?

**Comment by lacan** [comment]
Hi, 
Sorry for the delay. Indeed I got it to work with the ICE interface. However importing the images is terribly slow for now.

After I click on "Import XXX to QuPath", it takes 15-30s to go from Checking for compatible image readers, then to "Preparing to add 1 image to project"

I will still be testing the Microservice interface when out IT manages to install it.

**Comment by Rylern** [comment]
Thanks, I improved the performance of the Ice pixel API in the [v0.1.0-rc5 release](https://github.com/qupath/qupath-extension-omero/releases/tag/v0.1.0-rc5).

Some images might still take some time to open when their lowest resolution is big, but I cannot really do something about it. At least now the image opening duration should be the same as for the BIOP extension, and images should be faster to read because several readers are now used at the same time.
