### ISSUE TITLE
Error logs with extension installed, but using local images

### ISSUE THREAD

**Issue by psobolewskiPhD** [qupath/qupath-extension-omero#16]
Interacting with local images in a fresh QuPath that hasn't connected to the omero server I get accumulation of error logs:
```
13:20:43.651	[project-import1]	ERROR	qupath.ext.omero.core.RequestSender	Error when creating GET request	java.lang.IllegalArgumentException: invalid URI scheme file
	at java.net.http/jdk.internal.net.http.common.Utils.newIAE(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.checkURI(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.uri(Unknown Source)
	at java.net.http/jdk.internal.net.http.HttpRequestBuilderImpl.uri(Unknown Source)
	at qupath.ext.omero.core.RequestSender.getGETRequest(RequestSender.java:358)
	at qupath.ext.omero.core.RequestSender.isLinkReachableWithGet(RequestSender.java:74)
	at qupath.ext.omero.core.imageserver.OmeroImageServerBuilder.getClientAndCheckURIReachable(OmeroImageServerBuilder.java:87)
	at qupath.ext.omero.core.imageserver.OmeroImageServerBuilder.getImagesURIFromEntityURI(OmeroImageServerBuilder.java:110)
	at qupath.ext.omero.core.imageserver.OmeroImageServerBuilder.checkImageSupport(OmeroImageServerBuilder.java:36)
	at qupath.lib.images.servers.ImageServers.getImageSupport(ImageServers.java:387)
	at qupath.lib.images.servers.ImageServers.getAllImageSupports(ImageServers.java:360)
	at qupath.lib.images.servers.ImageServers.getImageSupport(ImageServers.java:402)
	at qupath.lib.gui.commands.ProjectImportImagesCommand$1.lambda$call$0(ProjectImportImagesCommand.java:362)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)


```

There are no symptoms, but it makes the error log icon less useful as it's constantly red.

**Comment by Rylern** [comment]
Thanks, it should be fixed in the [v0.1.0-rc4 release](https://github.com/qupath/qupath-extension-omero/releases/tag/v0.1.0-rc4)
